namespace SistemaRaro;

public enum Status
{
    EMAIL_EXISTENTE,
    SENHA_NAO_TEM_8_CARACTERES,
    SENHA_NAO_TEM_LETRA_MAIUSCULA,
    SENHA_NAO_TEM_CHAR_ESPECIAL,
    SENHA_NAO_TEM_NUMEROS,
    CONFIRMACAO_INVALIDA,
    USUARIO_VALIDO,
    CADASTRADO,
}
